alias connect-speaker="bluetoothctl connect 5C:FB:7C:C3:64:A8"
alias connect-headphones="bluetoothctl connect F8:AB:E5:46:36:17"
alias connect-earphones="bluetoothctl connect F4:4E:FD:00:05:02"
alias xclip="xclip -selection c"
alias weather="curl wttr.in/albuquerque"
alias nvimr-help="cat ~/.nvim-r.txt"
alias vim="nvim"
